name: Check Build Status


on:
  push:
    branches:
      - master
      - develop
    paths:
      - Source/**
    tags-ignore:
      # This will ignore release versions tagged with a version identifier. We'll 
      # use a separate workflow for them.
      - 'v*'

  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Build & Test v${{ matrix.rimworld-version }} on ${{ matrix.operating-system }}
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        rimworld-version: [1.4, 1.5]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4.2.1
      
    - name: Setup Dotnet
      uses: actions/setup-dotnet@v4.1.0
      with:
        dotnet-version: 8.0.x

    - name: Build Mod
      run: dotnet build Source/${{ matrix.rimworld-version }} --configuration Release

    - name: Test Mod
      run: dotnet test Source/${{ matrix.rimworld-version }} --configuration Release
